### ISSUE TITLE
Loglevel not completely respected?

### ISSUE THREAD

**Issue by rjmsilveira** [signalfx/signalfx-k8s-metrics-adapter#13]
Hi,
I followed Klog log levels, and was trying to reduce output of adapter.
I set the value to 1, and later to 0, and I am still seeing this (below) requested constantly (multiple times per second)
`I1023 14:17:03.802812       1 provider.go:169] ListAllMetrics() -> []`

Is this the normal expected behavior, and if so, how can we stop seeing that verbosity?

Thanks,

**Comment by keitwb** [comment]
I think the Helm chart would need to be enhanced to add a cli flag `minloglevel` and allow that to be configurable (the default is the lowest level). If you make a PR for that I would gladly accept it.

**Comment by keitwb** [comment]
The logs you are seeing come from [glog](https://godoc.org/github.com/golang/glog) and are from the k8s metrics adapter library that this app uses internally.  The possible flags are documented in the link.

**Comment by rjmsilveira** [comment]
Thanks for the reply.

I also took a look where this string was coming from and I noticed that https://github.com/signalfx/signalfx-k8s-metrics-adapter/blob/52d5080d63829bb1c43745a7506b01cda4c95be7/internal/provider.go#L169 shows it has no level like `V(5)`.
`klog.V(5).Infof("ListAllMetrics() -> %v", out) `
I believe this is the reason why it is showing this log no matter the value introduced.
