### ISSUE TITLE
[NoIssue] Question about errored_jobs

### ISSUE THREAD

**Issue by rjmsilveira** [signalfx/signalfx-k8s-metrics-adapter#14]
Hi, this is not necessarily an issue, but more a question.

Was testing the metrics exposed and noticed that I cannot make the metric errored_jobs be triggered.

I tried to make syntax errors within signalflow, setting all signals to false, and even make the Adapter fail to connect to SFx but I don't see it being activated.

Can you help me understand when should it be triggered?

Thanks in advance

**Comment by keitwb** [comment]
Are you collecting the metrics with the Smart Agent?  The adapter doesn't actually send metrics about itself directly, it just exposes them.

Also check if the logs have a message like `SignalFlow job errored, restarting in a bit:`.  If this displays, then there should definitely be some errors registering for the errored_jobs metric.  Also note that that metric is a cumulative metric so by default in charts it will show as a delta, which means it only shows the diff from the last interval sent.

**Comment by rjmsilveira** [comment]
Yes, we use Smart Agent polling metrics from adapter.
Meanwhile errors happened and we got alerts as expected. Thanks
