### ISSUE TITLE
no build yet for 0.8.0

### ISSUE THREAD

**Issue by gbucknel** [signalfx/signalfx-k8s-metrics-adapter#33]
Hi,

Thanks for merging our PR . We noticed that there's no corresponding build here yet? 
https://quay.io/repository/signalfx/k8s-metrics-adapter?tab=tags&tag=latest

Do we have to do something to kick off the docker build ? 
cc @benkeith-splunk 

Thank you!

**Comment by benkeith-splunk** [comment]
@gbucknel sorry about that. I pushed the image just now -- let me know if there are any further issues you find.
