### ISSUE TITLE
0.8.0 docker image is compiled for arm64 not amd64

### ISSUE THREAD

**Issue by gbucknel** [signalfx/signalfx-k8s-metrics-adapter#34]
Hi @benkeith-splunk 

Follow on from -> https://github.com/signalfx/signalfx-k8s-metrics-adapter/issues/33
Thanks for pushing that image yesterday, but went to try it out and found `adapter` is an arm64 binary, not a amd64 binary. Here's a checksum of the file and the output of file for 0.8.0 and 0.7.0
 
0.8.0 : 
```
sha256 md5sum adapter && file adapter
e17784dbea5ee4e2d498ad9b72657d68  adapter
adapter: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=fQavb7m5C1KI1OCWi3OX/-_iC3yYcZEPqUEXevOVq/aGItp8GhSyk_F6SusfTw/XDRSh1MnJS0hBLEwGXaK, with debug_info, not stripped
➜  sha256
```

0.7.0:
```
➜  sha256 md5sum adapter && file adapter
37b61b81fbeb286b281f882022cefd46  adapter
adapter: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=13-pSg0vcqjZ47LcLmy3/yQjnSXzKwwOlIOhr-ce6/cL15kdhzYfOvhICGHyga/U7A1SlUqHIHe3m7SOJbH, with debug_info, not stripped
➜  sha256
```

Also noticed the latest tag in the registry is still pointing at 0.7.0 , and the helm chart isn't updated to point at the new image (which I should've brought up yesterday also).
Thanks !

**Comment by benkeith-splunk** [comment]
Ok, I fixed the build process to make sure it always compiles it for amd64 and have pushed a new image and updated the latest tag.

I'll update the helm chart soon but I would definitely not recommend relying upon any `latest` tags or the defaults in the helm charts and rather would just pin the version to the one you want.
