### ISSUE TITLE
no build yet for 0.8.1

### ISSUE THREAD

**Issue by jrangel-rp** [signalfx/signalfx-k8s-metrics-adapter#42]
Can we get this docker image produced?

I saw that [a previous issue was opened](https://github.com/signalfx/signalfx-k8s-metrics-adapter/issues/33) to request this for 0.8.0 before.

I'm hoping that the fix introduced [in this PR](https://github.com/signalfx/signalfx-k8s-metrics-adapter/pull/41) will solve the problems we're having in our environments.

**Comment by jrangel-rp** [comment]
@benkeith-splunk?

**Comment by benkeith-splunk** [comment]
@jrangel-rp Sorry for the delay, the new build should be there now (0.8.1). Let me know if there are any further issues.

**Comment by jrangel-rp** [comment]
The build that was pushed is arm64?
I'm getting an error using:
docker pull --platform=linux/amd64 quay.io/signalfx/k8s-metrics-adapter:0.8.1
> image with reference quay.io/signalfx/k8s-metrics-adapter:0.8.1 was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64

**Comment by jrangel-rp** [comment]
@benkeith-splunk

**Comment by benkeith-splunk** [comment]
ok, try it again. This is apparently some new thing since the last release with docker where the images themselves have a platform. The binary within the image was amd64 but the docker image itself wasn't tagged as such. Should be so now.

**Comment by jrangel-rp** [comment]
Alright, the command didn't fail this time, but our pull-through cache is still showing the same error.
I'll update you once it pulls and/or we test it.
